In [3]:
import tensorflow as tf
import pandas as pd
import numpy as np 




In [4]:
t1= tf.constant(1)
t1

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [5]:
t1.numpy()

1

In [8]:
tf.rank(t1)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [9]:
t2=tf.constant([3,2,5,8])
t2

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 2, 5, 8])>

In [10]:
tf.rank(t2)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [13]:
t3=tf.constant([[1,2,3],[1,2,3],[1,2,3]])
t3

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])>

In [15]:
tv1=tf.Variable(t3)
tv1

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])>

In [16]:
tf.cast(tv1,tf.int32)

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])>

In [24]:
tv2=tf.Variable([2,4,6,8])
tv2

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([2, 4, 6, 8])>

In [25]:
tv2[2]

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [26]:
tv2[:3]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 4, 6])>

In [28]:
tv3=tf.random.normal([4,3])
tv3

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[-1.0396073 , -0.7284128 , -0.44439378],
       [-0.5317192 , -1.0723478 ,  0.89138937],
       [-2.0599008 ,  0.09579488, -1.2770326 ],
       [-0.2580842 ,  0.9488998 , -0.6517106 ]], dtype=float32)>

In [32]:
tv4=tf.Variable(tv3)
tv4

<tf.Variable 'Variable:0' shape=(4, 3) dtype=float32, numpy=
array([[-1.0396073 , -0.7284128 , -0.44439378],
       [-0.5317192 , -1.0723478 ,  0.89138937],
       [-2.0599008 ,  0.09579488, -1.2770326 ],
       [-0.2580842 ,  0.9488998 , -0.6517106 ]], dtype=float32)>

In [33]:
tv4[0,0].assign(0)

<tf.Variable 'UnreadVariable' shape=(4, 3) dtype=float32, numpy=
array([[ 0.        , -0.7284128 , -0.44439378],
       [-0.5317192 , -1.0723478 ,  0.89138937],
       [-2.0599008 ,  0.09579488, -1.2770326 ],
       [-0.2580842 ,  0.9488998 , -0.6517106 ]], dtype=float32)>

In [36]:
tv4[0,:].assign([1,1,1])

<tf.Variable 'UnreadVariable' shape=(4, 3) dtype=float32, numpy=
array([[ 1.        ,  1.        ,  1.        ],
       [-0.5317192 , -1.0723478 ,  0.89138937],
       [-2.0599008 ,  0.09579488, -1.2770326 ],
       [-0.2580842 ,  0.9488998 , -0.6517106 ]], dtype=float32)>

In [37]:
tf.ones([5,2])

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [39]:
tv4[tv4<0]

<tf.Tensor: shape=(6,), dtype=float32, numpy=
array([-0.5317192, -1.0723478, -2.0599008, -1.2770326, -0.2580842,
       -0.6517106], dtype=float32)>

In [40]:
tf.where(tv4<0)

<tf.Tensor: shape=(6, 2), dtype=int64, numpy=
array([[1, 0],
       [1, 1],
       [2, 0],
       [2, 2],
       [3, 0],
       [3, 2]], dtype=int64)>

In [41]:
a=tf.Variable([2,4,3])
b=tf.Variable([3,4,1])

a*b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 6, 16,  3])>

In [42]:
(a*b).numpy()

array([ 6, 16,  3])

In [43]:
tf.tensordot(a,b,0)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 6,  8,  2],
       [12, 16,  4],
       [ 9, 12,  3]])>

In [44]:
tf.add(a,b)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 8, 4])>

In [45]:
tf.cast(a,tf.float32)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 4., 3.], dtype=float32)>

In [46]:
tf.pow(a,2)


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4, 16,  9])>

In [52]:
tf.sqrt(tf.cast(tf.constant(9),'float32'))

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [57]:
a=tf.Variable(np.random.randint(1,5,[3,3]))
b=tf.Variable(np.random.randint(1,5,[3,3]))
a,b

(<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
 array([[4, 2, 1],
        [2, 4, 2],
        [1, 2, 3]])>,
 <tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
 array([[3, 3, 4],
        [2, 4, 2],
        [2, 3, 2]])>)